# Generated by Django 3.1.7 on 2021-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateTimeField(verbose_name='Expense Date')),
                ('category', models.CharField(choices=[('FD', 'Food'), ('SH', 'Shopping'), ('TR', 'Transport'), ('FU', 'Fuel'), ('EN', 'Entertainment'), ('HL', 'Health'), ('BL', 'Bills'), ('OT', 'Others')], default='OT', max_length=20, verbose_name='Expense Category')),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('amount', models.IntegerField(verbose_name='Expense Amount')),
                ('mode', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='OF', max_length=20, verbose_name='Payment Mode')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
