# Generated by Django 3.2.8 on 2021-10-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0002_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'FD'), ('Shopping', 'SH'), ('Transport', 'TR'), ('Fuel', 'FU'), ('Entertainment', 'EN'), ('Health', 'HL'), ('Bills', 'BL'), ('Others', 'OT')], default='OT', max_length=20, verbose_name='Expense Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mode',
            field=models.CharField(choices=[('Online', 'ON'), ('Offline', 'OFF')], default='OFF', max_length=20, verbose_name='Payment Mode'),
        ),
    ]
